# Generated by Django 2.2 on 2019-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword',
            name='sword_type',
            field=models.CharField(choices=[('rapier', 'Rapier'), ('feder', 'Feder'), ('longsword', 'Longsword Simulator'), ('other', 'Others')], max_length=20),
        ),
    ]
