# Generated by Django 2.2 on 2019-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190417_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword',
            name='sword_type',
            field=models.CharField(choices=[('Rapier', 'Rapier'), ('Feder', 'Feder'), ('Longsword Simulator', 'Longsword Simulator'), ('Other Weapon', 'Others')], max_length=20),
        ),
    ]
