# Generated by Django 2.2 on 2019-04-17 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190417_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Sword'),
        ),
    ]
